language: python
python:
  - "2.7"
install: sudo apt-get install inkscape librsvg2-bin
script: 
  - pwd
  - mkdir -p ~/.local/bin
  - ln -s /home/travis/build/winardiaris/pabrikon/bin/pabrikon.py /home/travis/.local/bin/pabrikon
  - ln -s /home/travis/build/winardiaris/pabrikon /opt/pabrikon
  - export PATH=$PATH:~/.local/bin
  - mkdir ~/tmp
  - cd ~/tmp
  - pabrikon --newproject --source=https://github.com/BlankOn/tebu-flat.git
  - cd tebu-flat/Tebu-Flat
  - pabrikon --makecsv
  - pabrikon -c
  - time pabrikon -b -t svg
  - pabrikon --makecsv
  - cd ~/tmp
  - pabrikon --newproject --source=https://github.com/BlankOn/Tebu.git
  - cd Tebu
  - pabrikon --makecsv
  - pabrikon -c
  - time pabrikon -b -t svg
